# Generated by Django 4.2.23 on 2025-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0002_categorias_alter_usuarios_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'gastos',
                'managed': False,
            },
        ),
    ]
