# Generated by Django 4.2.23 on 2025-07-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0003_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'managed': False,
            },
        ),
    ]
