# Generated by Django 4.2.23 on 2025-07-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0004_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolsos',
            fields=[
                ('id_reembolso', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'db_table': 'reembolsos',
                'managed': False,
            },
        ),
    ]
