# Generated by Django 4.2.23 on 2025-07-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0005_reembolsos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Reembolso',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('monto_aprobado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Reembolso',
                'verbose_name_plural': 'Detalles de Reembolso',
                'db_table': 'detalle_reembolso',
                'managed': False,
            },
        ),
    ]
